apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-eks-app
  namespace: actividad
  labels:
    app: jenkins-eks-app
spec:
  selector:
    matchLabels:
      app: jenkins-eks-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-eks-app
    spec:
      containers:
        - name: jenkins-eks-app
          image: 450280157612.dkr.ecr.us-east-1.amazonaws.com/rep-imagenes:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '500m'
