apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-eks-app
  labels:
    app: jenkins-eks-app
spec:
  selector:
    matchLabels:
        app: jenkins-eks-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-eks-app
    spec:
      containers:
        - name: jenkins-eks-app
          image:  450280157612.dkr.ecr.us-east-1.amazonaws.com/rep-imagenes:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always